version: '3.8'
services:
  web:
    build: .
    ports:
      - 3000:3000
    env_file: .env
    depends_on: 
      db:
        condition: service_healthy
    restart: on-failure
    environment:
      - DATABASE_URL={$DB_URL}
    volumes:
      - node_modules:/app/node_modules
  db:
    image: postgres:latest
    ports:
      - 35432:5432
    volumes:
       - postgres-data:/data/postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-mydb}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER:-user}

volumes:
  postgres-data:
  node_modules: 
